### ISSUE TITLE
Result object count parameter

### ISSUE THREAD

**Issue by zwalden** [Gueststream-Inc/VRPConnector#17]
I think data should be returned on the results page similar to: $data->results = fetchListings(count) (in addition to whatever other params it is passed..)

This approach will allow more freedom in theming the widget, in addition to providing a valuable configuration asset for designers wanting to have more (or less) listings shown for specific pages.

EDIT: tl;dr Need to be able to control the amount of objects so grids can be laid out (10 listings is not good for 4 columns, or 3 columns.. But 9 or 12 fit the bill.)

**Comment by jhoughtelin** [comment]
Working on it.  Give me a couple months and we'll be rolling out with more functional objects.  For now,  you're stuck =)
