### ISSUE TITLE
Guest or Owner Login Shortcode

### ISSUE THREAD

**Issue by Shahaan143** [Gueststream-Inc/VRPConnector#88]
I am Using VRPConnector Pro version. First of all its a Good Plugin and i am having a single problem that how can i show Guest and Owner login on my Webpage please let me know as soon as possible

Thanks

**Comment by jhoughtelin** [comment]
Guest and Owner logins are more often than not links that are pointed to your property management system.   What property management system are you connected to?

**Comment by Shahaan143** [comment]
i am using BAREFOOT

**Comment by jhoughtelin** [comment]
I'm most familiar with RNS owner and guest logins.  the VRPConnector itself is a booking tool that allows guests to book units through your site but it doesn't provide them (or the owner) the ability to login to the property management software.    Perhaps you just need to place a link on your site to the property management software login page?

**Comment by Shahaan143** [comment]
Ok Thanks For Your Time and REPLY 👍

**Comment by jhoughtelin** [comment]
No problem Shahaan143.  I asked our support how to get the links to the barefoot owner and guest login pages and they differed the question to Barefoot.  You'll be able to get the URL to the login pages from Barefoot support!
